* Notes
** Clustering

one way to solve single threaded node loop is using clustering

cluster manager checks the health and manages the instances of the node applications.
can start, stop.. administrate worker instances of our node applications.

the cluster manager require the cluster manager module.
*** Cluster Manager
cluster.fork() executes multiple times the same index.js file but creates a new worker instance

apache benchmark ~ab~
~ab -c 2 -n 4  localhost:3000/~

Note: 
don't over cluster!
try to match the children with the number of cpu threads

*** PM2 Cluster manager
pm2 is used mostly on production

installation:
#+begin_src 
 sudo npm i pm2 -g
#+end_src

examples of usage:

#+begin_src shell
pm2 start index.js -i 0
pm2 list               
pm2 show index         
pm2 monit              
pm2 delete index       
#+end_src

** Worker threads
* webworker-threads

Web workers are considered stables. [[https://nodejs.org/docs/latest-v16.x/api/worker_threads.html][Node 16 documentation.]] 
A lot of code usually uses libuv library and uses the threads on the machine.

The worker interface creates a worker thread and comunicates using postMessage and onmessage and will invoke the function assigned to the worker.

#+begin_src shell
ab -c 1 -n 1 localhost:3000
#+end_src




